import React,{useEffect,useMemo,useState} from 'react'
import {Search,Sparkles,SlidersHorizontal,X,ShieldCheck,Zap,Globe2,BarChart3,Heart,Bell,History,GitCompareArrows,ChevronRight,Trash2,ExternalLink,CheckCircle2,Menu,ArrowLeft,PackageSearch,Info} from 'lucide-react'
import {searchProducts,addWishlist,getWishlist,createAlert,getHistory,getAlerts,deleteAlert} from './api'
import ProductCard from './components/ProductCard'

const suggestions=['best laptop for coding under ₹60000','wireless headphones under ₹5000','running shoes under ₹3000','55 inch 4K smart TV','college backpack under ₹2000','stainless steel pressure cooker']
const money=n=>n==null?'—':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n)

function App(){
 const [query,setQuery]=useState(''); const [data,setData]=useState(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('')
 const [compare,setCompare]=useState([]); const [wishlist,setWishlist]=useState([]); const [sort,setSort]=useState('match'); const [maxPrice,setMaxPrice]=useState('')
 const [view,setView]=useState('home'); const [detail,setDetail]=useState(null); const [alertProduct,setAlertProduct]=useState(null); const [alertPrice,setAlertPrice]=useState('')
 const [history,setHistory]=useState([]); const [alerts,setAlerts]=useState([]); const [mobileNav,setMobileNav]=useState(false)

 useEffect(()=>{
   getWishlist().then(x=>setWishlist(x)).catch(()=>{})
   getHistory().then(setHistory).catch(()=>{})
   getAlerts().then(setAlerts).catch(()=>{})
 },[])
 async function runSearch(value=query){const q=value.trim();if(!q)return;setQuery(q);setLoading(true);setError('');setView('search');try{setData(await searchProducts(q));getHistory().then(setHistory).catch(()=>{})}catch(e){setError('BuySphere could not reach the backend. Start FastAPI on port 8000 and try again.')}finally{setLoading(false)}}
 async function toggleWishlist(p){
   if(wishlist.some(x=>x.id===p.id)){ if(p.id>=0) await fetch(`/api/wishlist/${p.id}`,{method:'DELETE'}); setWishlist(x=>x.filter(a=>a.id!==p.id)); return }
   if(p.id>=0){await addWishlist(p.id)}
   const item={...p};setWishlist(x=>[item,...x])
 }
 function addCompare(p){setCompare(x=>x.some(a=>a.id===p.id)?x:x.length<4?[...x,p]:x);setView('search')}
 const products=useMemo(()=>{let a=[...(data?.products||[])];if(maxPrice)a=a.filter(p=>p.best_price<=Number(maxPrice));if(sort==='price')a.sort((x,y)=>(x.best_price??Infinity)-(y.best_price??Infinity));if(sort==='rating')a.sort((x,y)=>(y.rating||0)-(x.rating||0));if(sort==='match')a.sort((x,y)=>(y.match_score||0)-(x.match_score||0));return a},[data,maxPrice,sort])
 async function makeAlert(){if(!alertProduct||!alertPrice)return;try{if(alertProduct.id>=0){await createAlert(alertProduct.id,Number(alertPrice))}const local={id:`local-${Date.now()}`,product_id:alertProduct.id,product_title:alertProduct.title,target_price:Number(alertPrice),active:true,created_at:new Date().toISOString()};setAlerts(a=>[local,...a]);setAlertProduct(null);setAlertPrice('')}catch(e){setError(e.message)}}
 async function removeAlert(a){if(typeof a.id==='number')await deleteAlert(a.id).catch(()=>{});setAlerts(x=>x.filter(y=>y.id!==a.id))}
 return <div className="app">
  <header className="nav"><button className="mobile-menu" onClick={()=>setMobileNav(!mobileNav)}><Menu/></button><button className="brand brand-btn" onClick={()=>{setView('home');setData(null)}}><div className="logo">B</div><span>Buy<span>Sphere</span></span><small>AI</small></button>
   <nav className={mobileNav?'nav-links open':'nav-links'}><button onClick={()=>{setView('home');setData(null);setMobileNav(false)}}>Home</button><button onClick={()=>{setView('wishlist');setMobileNav(false)}}>Wishlist</button><button onClick={()=>{setView('history');setMobileNav(false)}}>History</button><button onClick={()=>{setView('alerts');setMobileNav(false)}}>Alerts</button></nav>
   <div className="nav-actions"><button className="nav-icon" onClick={()=>setView('wishlist')}><Heart size={17}/><span>{wishlist.length}</span></button><button className="nav-icon" onClick={()=>setView('alerts')}><Bell size={17}/><span>{alerts.length}</span></button></div>
  </header>
  <main>
   {view==='home'&&<Home runSearch={runSearch} query={query} setQuery={setQuery}/>} 
   {view==='search'&&<SearchView data={data} products={products} query={query} setQuery={setQuery} runSearch={runSearch} loading={loading} error={error} setError={setError} sort={sort} setSort={setSort} maxPrice={maxPrice} setMaxPrice={setMaxPrice} wishlist={wishlist} toggleWishlist={toggleWishlist} addCompare={addCompare} setDetail={setDetail} setAlertProduct={setAlertProduct}/>} 
   {view==='wishlist'&&<WishlistView wishlist={wishlist} toggleWishlist={toggleWishlist} addCompare={addCompare} setDetail={setDetail} setAlertProduct={setAlertProduct} setView={setView}/>} 
   {view==='history'&&<HistoryView history={history} runSearch={runSearch}/>} 
   {view==='alerts'&&<AlertsView alerts={alerts} removeAlert={removeAlert}/>} 
  </main>
  {compare.length>0&&<CompareBar compare={compare} setCompare={setCompare} onOpen={()=>setDetail({type:'compare',products:compare})}/>} 
  {detail&&<DetailModal item={detail} close={()=>setDetail(null)}/>} 
  {alertProduct&&<AlertModal product={alertProduct} price={alertPrice} setPrice={setAlertPrice} close={()=>setAlertProduct(null)} save={makeAlert}/>} 
  <footer><div className="brand"><div className="logo">B</div><span>BuySphere</span></div><p>Search smarter. Compare better. Shop with confidence.</p><small>Full-stack shopping discovery platform</small></footer>
 </div>
}

function Home({runSearch,query,setQuery}){return <>
 <section className="hero"><div className="glow glow1"/><div className="glow glow2"/><div className="hero-badge"><Sparkles size={15}/> AI-powered shopping discovery</div><h1>Find <em>anything.</em><br/>Compare everything.</h1><p>Describe what you want in normal language. BuySphere searches connected shopping sources, analyzes the results, and puts prices, ratings and offers in one clean view.</p><div className="searchbox"><Search size={22}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&runSearch()} placeholder="Try “best laptop for coding under ₹60,000”"/><button onClick={()=>runSearch()}><Sparkles size={17}/> Search</button></div><div className="suggestions">{suggestions.map(s=><button key={s} onClick={()=>runSearch(s)}>{s}</button>)}</div><div className="hero-stats"><div><strong>Any product</strong><span>Search electronics, fashion, home, sports & more</span></div><div><strong>Live + catalog</strong><span>Connected shopping data with a reliable demo fallback</span></div><div><strong>Smart matching</strong><span>Intent, budget and product relevance in one score</span></div></div></section>
 <section className="features"><div className="section-heading"><span>BUILT FOR REAL SHOPPING</span><h2>Everything you need before you buy.</h2></div><div className="feature-grid"><Feature icon={<Globe2/>} title="Multi-source discovery" text="Bring supported retailer, feed and API results into one search experience."/><Feature icon={<Sparkles/>} title="Natural-language intent" text="Budget, product type and preferences are extracted from the way you ask."/><Feature icon={<BarChart3/>} title="Compare offers" text="See price, rating, reviews, retailer and specifications without opening ten tabs."/><Feature icon={<Bell/>} title="Price tracking" text="Create target-price alerts and keep your shopping history organized."/></div></section>
 <section className="trust"><div><ShieldCheck/><b>Transparent data</b><span>Retailer links always open at the source.</span></div><div><Zap/><b>Fast search</b><span>Parallel provider architecture keeps discovery quick.</span></div><div><PackageSearch/><b>Any category</b><span>Not locked to a fixed product list.</span></div></section>
 </>}
function SearchView({data,products,query,setQuery,runSearch,loading,error,setError,sort,setSort,maxPrice,setMaxPrice,wishlist,toggleWishlist,addCompare,setDetail,setAlertProduct}){return <section className="results"><div className="result-top"><div><button className="back" onClick={()=>{setError('');window.scrollTo(0,0)}}><ArrowLeft size={15}/> Search again</button><h2>Results for <span>“{data?.query||query}”</span></h2><p>{loading?'Analyzing connected shopping sources…':`${data?.total||0} products found`} {data?.interpreted?.category&&<> · category <b>{data.interpreted.category}</b></>} {data?.interpreted?.budget&&<> · budget <b>{money(data.interpreted.budget)}</b></>}</p></div><div className="searchbox compact"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&runSearch()}/><button onClick={()=>runSearch()}>Search</button></div></div>{error&&<div className="error"><Info size={18}/>{error}<button onClick={()=>setError('')}><X size={15}/></button></div>}<div className="toolbar"><div className="filters"><SlidersHorizontal size={17}/><b>Filter</b><input type="number" placeholder="Max price ₹" value={maxPrice} onChange={e=>setMaxPrice(e.target.value)}/>{maxPrice&&<button onClick={()=>setMaxPrice('')}>Clear</button>}</div><select value={sort} onChange={e=>setSort(e.target.value)}><option value="match">Best match</option><option value="price">Lowest price</option><option value="rating">Highest rating</option></select></div>{loading?<div className="loading"><div className="spinner"/><h3>Finding matching products…</h3><p>Checking connected shopping data and ranking the results.</p></div>:<><div className="product-grid">{products.map(p=><ProductCard key={p.id} product={p} liked={wishlist.some(x=>x.id===p.id)} onWishlist={toggleWishlist} onCompare={addCompare} onDetails={setDetail} onAlert={setAlertProduct}/>)}</div>{!products.length&&<div className="empty"><PackageSearch size={40}/><h3>No matching products</h3><p>Try a broader product name or remove the price limit.</p></div>}</>}</section>}
function WishlistView({wishlist,toggleWishlist,addCompare,setDetail,setAlertProduct,setView}){return <section className="page"><PageTitle icon={<Heart/>} title="Your wishlist" text={`${wishlist.length} saved product${wishlist.length===1?'':'s'}.`}/>{wishlist.length?<div className="product-grid">{wishlist.map(p=><ProductCard key={p.id} product={p} liked onWishlist={toggleWishlist} onCompare={addCompare} onDetails={setDetail} onAlert={setAlertProduct}/>)}</div>:<Empty icon={<Heart/>} title="Your wishlist is empty" text="Save products while you search and they will appear here." action={()=>setView('home')}/>}</section>}
function HistoryView({history,runSearch}){return <section className="page"><PageTitle icon={<History/>} title="Search history" text="Jump back into your recent shopping research."/>{history.length?<div className="history-list">{history.map((h,i)=><button key={i} onClick={()=>runSearch(h.query)}><History size={17}/><span>{h.query}</span><small>{new Date(h.created_at).toLocaleString()}</small><ChevronRight/></button>)}</div>:<Empty icon={<History/>} title="No searches yet" text="Your recent searches will appear here."/>}</section>}
function AlertsView({alerts,removeAlert}){return <section className="page"><PageTitle icon={<Bell/>} title="Price alerts" text="Target prices you are watching."/>{alerts.length?<div className="alert-list">{alerts.map(a=><div className="alert-row" key={a.id}><div className="alert-icon"><Bell size={18}/></div><div><b>{a.product_title}</b><span>Notify at {money(a.target_price)}</span></div><button onClick={()=>removeAlert(a)}><Trash2 size={17}/></button></div>)}</div>:<Empty icon={<Bell/>} title="No price alerts" text="Open any product and set a target price."/>}</section>}
function PageTitle({icon,title,text}){return <div className="page-title"><div className="page-icon">{icon}</div><div><span>MY SHOPPING</span><h2>{title}</h2><p>{text}</p></div></div>}
function Empty({icon,title,text,action}){return <div className="empty large">{icon}<h3>{title}</h3><p>{text}</p>{action&&<button className="primary" onClick={action}>Start searching</button>}</div>}
function Feature({icon,title,text}){return <div className="feature"><div className="feature-icon">{icon}</div><h3>{title}</h3><p>{text}</p></div>}
function CompareBar({compare,setCompare,onOpen}){return <div className="comparebar"><div className="compare-info"><GitCompareArrows/><div><b>Compare products</b><span>{compare.length}/4 selected</span></div></div><div className="compare-items">{compare.map(p=><button key={p.id} onClick={()=>setCompare(x=>x.filter(a=>a.id!==p.id))}>{p.title.slice(0,22)} <X size={12}/></button>)}</div><button className="primary" onClick={onOpen}>Compare now</button></div>}
function DetailModal({item,close}){if(item.type==='compare')return <div className="modal-backdrop"><div className="modal modal-wide"><button className="modal-x" onClick={close}><X/></button><div className="modal-heading"><GitCompareArrows/><div><span>BUYSPHERE ANALYSIS</span><h2>Side-by-side comparison</h2></div></div><div className="comparison-grid">{item.products.map(p=><div className="compare-card" key={p.id}><img src={p.image_url}/><b>{p.title}</b><strong>{money(p.best_price)}</strong><span>{p.rating?`★ ${p.rating.toFixed(1)}`:'No rating'} · {(p.review_count||0).toLocaleString('en-IN')} reviews</span><div>{Object.entries(p.specs||{}).slice(0,6).map(([k,v])=><p key={k}><small>{k}</small><b>{String(v)}</b></p>)}</div><a href={p.offers?.[0]?.product_url||'#'} target="_blank" rel="noreferrer">Open retailer <ExternalLink size={13}/></a></div>)}</div></div></div>
 return <div className="modal-backdrop"><div className="modal modal-wide"><button className="modal-x" onClick={close}><X/></button><div className="detail-layout"><img src={item.image_url}/><div><div className="eyebrow">{item.brand} · {item.category}</div><h2>{item.title}</h2><div className="rating">★ {item.rating?.toFixed(1)||'New'} · {(item.review_count||0).toLocaleString('en-IN')} reviews</div><div className="detail-price">{money(item.best_price)}</div><p>{item.description}</p><h4>Specifications</h4><div className="spec-grid">{Object.entries(item.specs||{}).map(([k,v])=><div key={k}><span>{k}</span><b>{String(v)}</b></div>)}</div><h4>Available offers</h4>{(item.offers||[]).map((o,i)=><div className="offer" key={i}><b>{o.store}</b><strong>{money(o.price)}</strong><span>{o.availability}</span><a href={o.product_url} target="_blank" rel="noreferrer">Open <ExternalLink size={13}/></a></div>)}</div></div></div></div>}
function AlertModal({product,price,setPrice,close,save}){return <div className="modal-backdrop"><div className="modal"><button className="modal-x" onClick={close}><X/></button><div className="modal-heading"><Bell/><div><span>PRICE TRACKER</span><h2>Set a target price</h2></div></div><p>We’ll keep this target in BuySphere. For live provider results, the retailer page remains the source of truth for current price.</p><div className="alert-product"><img src={product.image_url}/><b>{product.title}</b><span>Current: {money(product.best_price)}</span></div><input type="number" min="1" placeholder="Target price ₹" value={price} onChange={e=>setPrice(e.target.value)}/><button className="primary wide" disabled={!price} onClick={save}>Create price alert</button></div></div>}
export default App
